import { TypographyComponentToken } from '../atomics';
import { AvatarComponentToken } from './Avatar';
import { BreadcrumbComponentToken } from './Breadcrumb';
import { ButtonComponentToken } from './Button';
import { CardComponentToken } from './Card';
import { CheckboxComponentToken } from './Checkbox';
import { CollapseComponentToken } from './Collapse';
import { DividerComponentToken } from './Divider';
import { DrawerComponentToken } from './Drawer';
import { DropdownComponentToken } from './Dropdown';
import { FloatButtonComponentToken } from './FloatButton';
import { FormComponentToken } from './Form';
import { InputComponentToken } from './Input';
import { InputNumberComponentToken } from './InputNumber';
import { LayoutComponentToken } from './Layout';
import { MenuComponentToken } from './Menu';
import { ModalComponentToken } from './Modal';
import { PaginationComponentToken } from './Pagination';
import { PopoverComponentToken } from './Popover';
import { RadioComponentToken } from './Radio';
import { DatePickerComponentToken } from './RangePicker';
import { SelectComponentToken } from './Select';
import { SkeletonComponentToken } from './Skeleton';
import { SliderComponentToken } from './Slider';
import { SpaceComponentToken } from './Space';
import { SpinComponentToken } from './Spin';
import { SwitchComponentToken } from './Switch';
import { TableComponentToken } from './Table';
import { TabsComponentToken } from './Tabs';
import { TooltipComponentToken } from './Tooltip';
import { UploadComponentToken } from './Upload';

export interface RdComponentTokenMap {
    // Affix?: AffixComponentToken;
    // Alert?: AlertComponentToken;
    // Anchor?: AnchorComponentToken;
    Avatar?: AvatarComponentToken;
    // BackTop?: BackTopComponentToken;
    // Badge?: BadgeComponentToken;
    Button?: ButtonComponentToken;
    Breadcrumb?: BreadcrumbComponentToken;
    Card?: CardComponentToken;
    // Carousel?: CarouselComponentToken;
    // Cascader?: CascaderComponentToken;
    Checkbox?: CheckboxComponentToken;
    // ColorPicker?: ColorPickerComponentToken;
    Collapse?: CollapseComponentToken;
    DatePicker?: DatePickerComponentToken;
    // Descriptions?: DescriptionsComponentToken;
    Divider?: DividerComponentToken;
    Drawer?: DrawerComponentToken;
    Dropdown?: DropdownComponentToken;
    // Empty?: EmptyComponentToken;
    // Flex?: FlexComponentToken;
    FloatButton?: FloatButtonComponentToken;
    Form?: FormComponentToken;
    // Grid?: GridComponentToken;
    // Image?: ImageComponentToken;
    Input?: InputComponentToken;
    InputNumber?: InputNumberComponentToken;
    Layout?: LayoutComponentToken;
    // List?: ListComponentToken;
    // Mentions?: MentionsComponentToken;
    // Notification?: NotificationComponentToken;
    Pagination?: PaginationComponentToken;
    Popover?: PopoverComponentToken;
    // Popconfirm?: PopconfirmComponentToken;
    // Rate?: RateComponentToken;
    Radio?: RadioComponentToken;
    // Result?: ResultComponentToken;
    // Segmented?: SegmentedComponentToken;
    Select?: SelectComponentToken;
    Skeleton?: SkeletonComponentToken;
    Slider?: SliderComponentToken;
    Spin?: SpinComponentToken;
    // Statistic?: StatisticComponentToken;
    Switch?: SwitchComponentToken;
    // Splitter?: SplitterComponentToken;
    // Tag?: TagComponentToken;
    // Tree?: TreeComponentToken;
    // TreeSelect?: TreeSelectComponentToken;
    Typography?: TypographyComponentToken;
    // Timeline?: TimelineComponentToken;
    // Transfer?: TransferComponentToken;
    Tabs?: TabsComponentToken;
    // Calendar?: CalendarComponentToken;
    // Steps?: StepsComponentToken;
    Menu?: MenuComponentToken;
    Modal?: ModalComponentToken;
    // Message?: MessageComponentToken;
    Upload?: UploadComponentToken;
    Tooltip?: TooltipComponentToken;
    Table?: TableComponentToken;
    Space?: SpaceComponentToken;
    // Progress?: ProgressComponentToken;
    // Tour?: TourComponentToken;
    // QRCode?: QRCodeComponentToken;
    // App?: AppComponentToken;
    /** @private Internal TS definition. Do not use. */
    // Wave?: WaveToken;
}
